### ISSUE TITLE
[NEW STOCK]CORTEX (CTXC/USDT) BINANCE

### ISSUE THREAD

**Issue by effofxprime** [rssnyder/discord-stock-ticker-bot#4]
Requesting an add for Cortex ticker, CTXC/USDT.
Thank you!

**Comment by rssnyder** [comment]
This is the wrong repo, please see https://github.com/rssnyder/discord-stock-ticker

You can find the bots you want, or request more to be created, by joining the support server. The link is in the readme of the repo I linked above.
